version: '3.9'
services:
  app:
    container_name: unith-assignment-front
    image: andriinadosha/unith-assignment
    working_dir: /app/unith-assignment
    command: yarn start
    build:
      context: ./front-end
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: unith-assignment-server
    image: andriinadosha/unith-assignment-server
    working_dir: /app/unith-assignment/server
    command: npm start
    build:
      context: ./server
    ports:
      - '3001:3001'

